package com.tylerthardy.taskstracker.bosses;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Boss
{
	ABYSSAL_SIRE("Abyssal Sire"),
	AGILITY_ARENA("Agility Arena"),
	AGILITY_PYRAMID("Agility Pyramid"),
	AL_KHARID_ROOFTOP("Al-Kharid Rooftop"),
	ALCHEMICAL_HYDRA("Alchemical Hydra"),
	APE_ATOLL_AGILITY("Ape Atoll Agility"),
	ARDOUGNE_ROOFTOP("Ardougne Rooftop"),
	BARBARIAN_OUTPOST("Barbarian Outpost"),
	BARROWS_CHESTS("Barrows Chests"),
	BRYOPHYTA("Bryophyta"),
	CANIFIS_ROOFTOP("Canifis Rooftop"),
	CALLISTO("Callisto"),
	CERBERUS("Cerberus"),
	CHAMBERS_OF_XERIC_CHALLENGE_MODE("Chambers of Xeric Challenge Mode"),
	CHAMBERS_OF_XERIC("Chambers of Xeric"),
	CHAOS_ELEMENTAL("Chaos Elemental"),
	CHAOS_FANATIC("Chaos Fanatic"),
	COMMANDER_ZILYANA("Commander Zilyana"),
	CORPOREAL_BEAST("Corporeal Beast"),
	CRAZY_ARCHAEOLOGIST("Crazy Archaeologist"),
	DAGANNOTH_PRIME("Dagannoth Prime"),
	DAGANNOTH_REX("Dagannoth Rex"),
	DAGANNOTH_SUPREME("Dagannoth Supreme"),
	DERANGED_ARCHAEOLOGIST("Deranged Archaeologist"),
	DORGESH_KAAN_AGILITY("Dorgesh-Kaan Agility"),
	DRAYNOR_VILLAGE_ROOFTOP("Draynor Village Rooftop"),
	FALADOR_ROOFTOP("Falador Rooftop"),
	GENERAL_GRAARDOR("General Graardor"),
	GIANT_MOLE("Giant Mole"),
	GNOME_STRONGHOLD_AGILITY("Gnome Stronghold Agility"),
	GROTESQUE_GUARDIANS("Grotesque Guardians"),
	HALLOWED_SEPULCHRE_FLOOR_1("Hallowed Sepulchre Floor 1"),
	HALLOWED_SEPULCHRE_FLOOR_2("Hallowed Sepulchre Floor 2"),
	HALLOWED_SEPULCHRE_FLOOR_3("Hallowed Sepulchre Floor 3"),
	HALLOWED_SEPULCHRE_FLOOR_4("Hallowed Sepulchre Floor 4"),
	HALLOWED_SEPULCHRE_FLOOR_5("Hallowed Sepulchre Floor 5"),
	HALLOWED_SEPULCHRE("Hallowed Sepulchre"),
	HERBIBOAR("Herbiboar"),
	HESPORI("Hespori"),
	K_RIL_TSUTSAROTH("K'ril Tsutsaroth"),
	KALPHITE_QUEEN("Kalphite Queen"),
	KING_BLACK_DRAGON("King Black Dragon"),
	KRAKEN("Kraken"),
	KREE_ARRA("Kree'arra"),
	MIMIC("Mimic"),
	NEX("Nex"),
	OBOR("Obor"),
	PENGUIN_AGILITY("Penguin Agility"),
	PHOSANI_S_NIGHTMARE("Phosani's Nightmare"),
	POLLNIVNEACH_ROOFTOP("Pollnivneach Rooftop"),
	PRIFDDINAS_AGILITY_COURSE("Prifddinas Agility Course"),
	RELLEKKA_ROOFTOP("Rellekka Rooftop"),
	SARACHNIS("Sarachnis"),
	SCORPIA("Scorpia"),
	SEERS__VILLAGE_ROOFTOP("Seers' Village Rooftop"),
	SKOTIZO("Skotizo"),
	TEMPOROSS("Tempoross"),
	THE_CORRUPTED_GAUNTLET("The Corrupted Gauntlet"),
	THE_GAUNTLET("The Gauntlet"),
	THE_NIGHTMARE("Nightmare"),
	THEATRE_OF_BLOOD_ENTRY_MODE("Theatre of Blood Entry Mode"),
	THEATRE_OF_BLOOD_HARD_MODE("Theatre of Blood Hard Mode"),
	THEATRE_OF_BLOOD("Theatre of Blood"),
	THERMONUCLEAR_SMOKE_DEVIL("Thermonuclear Smoke Devil"),
	TZHAAR_KET_RAK_S_FIFTH_CHALLENGE("TzHaar-Ket-Rak's Fifth Challenge"),
	TZHAAR_KET_RAK_S_FIRST_CHALLENGE("TzHaar-Ket-Rak's First Challenge"),
	TZHAAR_KET_RAK_S_FOURTH_CHALLENGE("TzHaar-Ket-Rak's Fourth Challenge"),
	TZHAAR_KET_RAK_S_SECOND_CHALLENGE("TzHaar-Ket-Rak's Second Challenge"),
	TZHAAR_KET_RAK_S_SIXTH_CHALLENGE("TzHaar-Ket-Rak's Sixth Challenge"),
	TZHAAR_KET_RAK_S_THIRD_CHALLENGE("TzHaar-Ket-Rak's Third Challenge"),
	TZKAL_ZUK("TzKal-Zuk"),
	TZTOK_JAD("TzTok-Jad"),
	VARROCK_ROOFTOP("Varrock Rooftop"),
	VENENATIS("Venenatis"),
	VET_ION("Vet'ion"),
	VORKATH("Vorkath"),
	WEREWOLF_AGILITY("Werewolf Agility"),
	WEREWOLF_SKULLBALL("Werewolf Skullball"),
	WILDERNESS_AGILITY("Wilderness Agility"),
	WINTERTODT("Wintertodt"),
	ZALCANO("ZALCANO"),
	ZULRAH("Zulrah");


	public String displayName;
}
