package com.tylerthardy.combattaskstracker;

public enum CombatTask {

    NOXIOUS_FOE("Noxious Foe", TaskTier.EASY, "Aberrant spectre", "Kill an Aberrant Spectre."),
    BARROWS_NOVICE("Barrows Novice", TaskTier.EASY, "Barrows", "Open the Barrows chest 10 times."),
    DEFENCE_WHAT_DEFENCE("Defence? What Defence?", TaskTier.EASY, "Barrows", "Kill any Barrows Brother using only magical damage."),
    BIG_BLACK_AND_FIERY("Big, Black and Fiery", TaskTier.EASY, "Black dragon", "Kill a Black Dragon."),
    THE_DEMONIC_PUNCHING_BAG("The Demonic Punching Bag", TaskTier.EASY, "Bloodveld", "Kill a Bloodveld."),
    BRYOPHYTA_NOVICE("Bryophyta Novice", TaskTier.EASY, "Bryophyta", "Kill Bryophyta once."),
    PROTECTION_FROM_MOSS("Protection from Moss", TaskTier.EASY, "Bryophyta", "Kill Bryophyta with the Protect from Magic prayer active."),
    PREPARATION_IS_KEY("Preparation Is Key", TaskTier.EASY, "Bryophyta", "Kill Bryophyta without suffering any poison damage."),
    A_SLOW_DEATH("A Slow Death", TaskTier.EASY, "Bryophyta", "Kill Bryophyta with either poison or venom being the final source of damage."),
    FIGHTING_AS_INTENDED_II("Fighting as Intended II", TaskTier.EASY, "Bryophyta", "Kill Bryophyta on a free to play world."),
    DERANGED_ARCHAEOLOGIST_NOVICE("Deranged Archaeologist Novice", TaskTier.EASY, "Deranged archaeologist", "Kill the Deranged Archaeologist 10 times."),
    THE_WALKING_VOLCANO("The Walking Volcano", TaskTier.EASY, "Fire giant", "Kill a Fire Giant."),
    INTO_THE_DEN_OF_GIANTS("Into the Den of Giants", TaskTier.EASY, "Hill Giant", "Kill a Hill Giant, Moss Giant and Fire Giant in the Giant Cave within the Shayzien region."),
    A_GREATER_FOE("A Greater Foe", TaskTier.EASY, "Greater demon", "Kill a Greater Demon."),
    NOT_SO_GREAT_AFTER_ALL("Not So Great After All", TaskTier.EASY, "Greater demon", "Finish off a Greater Demon with a demonbane weapon."),
    A_DEMONS_BEST_FRIEND("A Demon's Best Friend", TaskTier.EASY, "Hellhound", "Kill a Hellhound."),
    OBOR_NOVICE("Obor Novice", TaskTier.EASY, "Obor", "Kill Obor once."),
    SLEEPING_GIANT("Sleeping Giant", TaskTier.EASY, "Obor", "Kill Obor whilst he is immobilized."),
    FIGHTING_AS_INTENDED("Fighting as Intended", TaskTier.EASY, "Obor", "Kill Obor on a free to play world."),
    KING_BLACK_DRAGON_NOVICE("King Black Dragon Novice", TaskTier.EASY, "King Black Dragon", "Kill the King Black Dragon 10 times."),
    A_SCALEY_ENCOUNTER("A Scaley Encounter", TaskTier.EASY, "Lizardman shaman", "Kill a Lizardman Shaman."),
    SHAYZIEN_PROTECTOR("Shayzien Protector", TaskTier.EASY, "Lizardman shaman", "Kill a Lizardman Shaman in Molch which has not dealt damage to anyone. (excluding it's Spawns)"),
    GIANT_MOLE_NOVICE("Giant Mole Novice", TaskTier.EASY, "Giant Mole", "Kill the Giant Mole 10 times."),
    SARACHNIS_NOVICE("Sarachnis Novice", TaskTier.EASY, "Sarachnis", "Kill Sarachnis 10 times."),
    WINTERTODT_NOVICE("Wintertodt Novice", TaskTier.EASY, "Wintertodt", "Subdue the Wintertodt 10 times."),
    MUMMY("Mummy!", TaskTier.EASY, "Wintertodt", "Heal a pyromancer after they have fallen."),
    HANDYMAN("Handyman", TaskTier.EASY, "Wintertodt", "Repair a brazier which has been destroyed by the Wintertodt."),
    COSY("Cosy", TaskTier.EASY, "Wintertodt", "Subdue the Wintertodt with four pieces of warm equipment equipped."),
    A_SLITHERY_ENCOUNTER("A Slithery Encounter", TaskTier.EASY, "Wyrm", "Kill a Wyrm."),
    TEMPOROSS_NOVICE("Tempoross Novice", TaskTier.EASY, "Tempoross", "Subdue Tempoross 10 times."),
    MASTER_OF_BUCKETS("Master of Buckets", TaskTier.EASY, "Tempoross", "Extinguish at least 5 fires during a single Tempoross fight."),
    CALM_BEFORE_THE_STORM("Calm Before the Storm", TaskTier.EASY, "Tempoross", "Repair either a mast or a totem pole."),
    FIRE_IN_THE_HOLE("Fire in the Hole!", TaskTier.EASY, "Tempoross", "Attack Tempoross from both sides by loading both cannons on both ships."),
    SIT_BACK_AND_RELAX("Sit Back and Relax", TaskTier.MEDIUM, "Thrall", "Deal 100 damage to creatures using undead thralls."),
    BARROWS_CHAMPION("Barrows Champion", TaskTier.MEDIUM, "Barrows", "Open the Barrows chest 50 times."),
    CANT_TOUCH_ME("Can't Touch Me", TaskTier.MEDIUM, "Barrows", "Kill Dharok, Verac, Torag and Guthan without letting them attack you with melee and loot the chest."),
    PRAY_FOR_SUCCESS("Pray for Success", TaskTier.MEDIUM, "Barrows", "Kill all six Barrows Brothers and loot the Barrows chest without taking any damage from any of the brothers."),
    BRUTAL_BIG_BLACK_AND_FIREY("Brutal, Big, Black and Firey", TaskTier.MEDIUM, "Brutal black dragon", "Kill a Brutal Black Dragon."),
    BRYOPHYTA_CHAMPION("Bryophyta Champion", TaskTier.MEDIUM, "Bryophyta", "Kill Bryophyta 5 times."),
    QUICK_CUTTER("Quick Cutter", TaskTier.MEDIUM, "Bryophyta", "Kill all 3 of Bryophyta's growthlings within 3 seconds of the first one dying."),
    DEMONIC_WEAKENING("Demonic Weakening", TaskTier.MEDIUM, "Skotizo", "Kill Skotizo with no altars active."),
    DEMONBANE_WEAPONRY("Demonbane Weaponry", TaskTier.MEDIUM, "Skotizo", "Kill Skotizo with demonbane weapon equipped."),
    CHAOS_FANATIC_CHAMPION("Chaos Fanatic Champion", TaskTier.MEDIUM, "Chaos Fanatic", "Kill the Chaos Fanatic 10 times."),
    SORRY_WHAT_WAS_THAT("Sorry, What Was That?", TaskTier.MEDIUM, "Chaos Fanatic", "Kill the Chaos Fanatic without anyone being hit by his explosion attack."),
    CRAZY_ARCHAEOLOGIST_CHAMPION("Crazy Archaeologist Champion", TaskTier.MEDIUM, "Crazy archaeologist", "Kill the Crazy Archaeologist 10 times."),
    MAGE_OF_THE_RUINS("Mage of the Ruins", TaskTier.MEDIUM, "Crazy archaeologist", "Kill the Crazy Archaeologist with only magical attacks."),
    ID_RATHER_NOT_LEARN("I'd Rather Not Learn", TaskTier.MEDIUM, "Crazy archaeologist", "Kill the Crazy Archaeologist without anyone being hit by his \"Rain of Knowledge\" attack."),
    DERANGED_ARCHAEOLOGIST_CHAMPION("Deranged Archaeologist Champion", TaskTier.MEDIUM, "Deranged archaeologist", "Kill the Deranged Archaeologist 50 times."),
    MAGE_OF_THE_SWAMP("Mage of the Swamp", TaskTier.MEDIUM, "Deranged archaeologist", "Kill the Deranged Archaeologist with only magical attacks."),
    ID_RATHER_BE_ILLITERATE("I'd Rather Be Illiterate", TaskTier.MEDIUM, "Deranged archaeologist", "Kill the Deranged Archaeologist without anyone being hit by his \"Learn to Read\" attack."),
    A_SMASHING_TIME("A Smashing Time", TaskTier.MEDIUM, "Gargoyle", "Kill a Gargoyle."),
    OBOR_CHAMPION("Obor Champion", TaskTier.MEDIUM, "Obor", "Kill Obor 5 times."),
    BACK_TO_THE_WALL("Back to the Wall", TaskTier.MEDIUM, "Obor", "Kill Obor without being pushed back more than one square by his knockback attack."),
    SQUASHING_THE_GIANT("Squashing the Giant", TaskTier.MEDIUM, "Obor", "Kill Obor without taking any damage off prayer."),
    KING_BLACK_DRAGON_CHAMPION("King Black Dragon Champion", TaskTier.MEDIUM, "King Black Dragon", "Kill the King Black Dragon 50 times."),
    CLAW_CLIPPER("Claw Clipper", TaskTier.MEDIUM, "King Black Dragon", "Kill the King Black Dragon with the Protect from Melee prayer activated."),
    HIDE_PENETRATION("Hide Penetration", TaskTier.MEDIUM, "King Black Dragon", "Kill the King Black Dragon with a stab weapon."),
    ANTIFIRE_PROTECTION("Antifire Protection", TaskTier.MEDIUM, "King Black Dragon", "Kill the King Black Dragon with an antifire potion active and an antidragon shield equipped."),
    MASTER_OF_BROAD_WEAPONRY("Master of Broad Weaponry", TaskTier.MEDIUM, "Kurask", "Kill a Kurask."),
    GIANT_MOLE_CHAMPION("Giant Mole Champion", TaskTier.MEDIUM, "Giant Mole", "Kill the Giant mole 50 times."),
    AVOIDING_THOSE_LITTLE_ARMS("Avoiding Those Little Arms", TaskTier.MEDIUM, "Giant Mole", "Kill the Giant Mole without her damaging anyone."),
    DAGANNOTH_PRIME_CHAMPION("Dagannoth Prime Champion", TaskTier.MEDIUM, "Dagannoth Prime", "Kill Dagannoth Prime 50 times."),
    DAGANNOTH_REX_CHAMPION("Dagannoth Rex Champion", TaskTier.MEDIUM, "Dagannoth Rex", "Kill Dagannoth Rex 50 times."),
    A_FROZEN_KING("A Frozen King", TaskTier.MEDIUM, "Dagannoth Rex", "Kill Dagannoth Rex whilst he is immoblized."),
    SARACHNIS_CHAMPION("Sarachnis Champion", TaskTier.MEDIUM, "Sarachnis", "Kill Sarachnis 50 times."),
    NEWSPAPER_ENTHUSIAST("Newspaper Enthusiast", TaskTier.MEDIUM, "Sarachnis", "Kill Sarachnis with a crush weapon."),
    A_FROZEN_FOE_FROM_THE_PAST("A Frozen Foe from the Past", TaskTier.MEDIUM, "Skeletal Wyvern", "Kill a Skeletal Wyvern"),
    DAGANNOTH_SUPREME_CHAMPION("Dagannoth Supreme Champion", TaskTier.MEDIUM, "Dagannoth Supreme", "Kill Dagannoth Supreme 50 times."),
    WINTERTODT_CHAMPION("Wintertodt Champion", TaskTier.MEDIUM, "Wintertodt", "Subdue the Wintertodt 50 times."),
    CAN_WE_FIX_IT("Can We Fix It?", TaskTier.MEDIUM, "Wintertodt", "Subdue the Wintertodt without allowing all 4 braziers to be broken at the same time."),
    LEAVING_NO_ONE_BEHIND("Leaving No One Behind", TaskTier.MEDIUM, "Wintertodt", "Subdue the Wintertodt without any of the Pyromancers falling."),
    SKOTIZO_ADEPT("Skotizo Adept", TaskTier.MEDIUM, "Skotizo", "Kill Skotizo once."),
    TEMPOROSS_CHAMPION("Tempoross Champion", TaskTier.MEDIUM, "Tempoross", "Subdue Tempoross 50 times."),
    THE_LONE_ANGLER("The Lone Angler", TaskTier.MEDIUM, "Tempoross", "Subdue Tempoross alone without getting hit by any fires, torrents or waves."),
    ABYSSAL_ADEPT("Abyssal Adept", TaskTier.HARD, "Abyssal Sire", "Kill the Abyssal Sire 100 times."),
    THEY_GROW_UP_TOO_FAST("They Grow Up Too Fast", TaskTier.HARD, "Abyssal Sire", "Kill the Abyssal Sire without letting any Scion mature."),
    DONT_WHIP_ME("Don't Whip Me", TaskTier.HARD, "Abyssal Sire", "Kill the Abyssal Sire without being hit by any external tentacles."),
    DONT_STOP_MOVING("Don't Stop Moving", TaskTier.HARD, "Abyssal Sire", "Kill the Abyssal Sire without taking damage from any miasma pools."),
    KREEARRA_ADEPT("Kree'arra Adept", TaskTier.HARD, "Kree'arra", "Kill Kree'arra 50 times."),
    AIRBORNE_SHOWDOWN("Airborne Showdown", TaskTier.HARD, "Kree'arra", "Finish off Kree'arra whilst all of his bodyguards are dead."),
    GENERAL_GRAARDOR_ADEPT("General Graardor Adept", TaskTier.HARD, "General Graardor", "Kill General Graardor 50 times."),
    OURG_FREEZER("Ourg Freezer", TaskTier.HARD, "General Graardor", "Kill General Graardor whilst he is immobilized."),
    GENERAL_SHOWDOWN("General Showdown", TaskTier.HARD, "General Graardor", "Finish off General Graardor whilst all of his bodyguards are dead."),
    JUST_LIKE_THAT("Just Like That", TaskTier.HARD, "Barrows", "Kill Karil using only damage dealt by special attacks."),
    FAITHLESS_CRYPT_RUN("Faithless Crypt Run", TaskTier.HARD, "Barrows", "Kill all six Barrows Brothers and loot the Barrows chest without ever having more than 0 prayer points."),
    CALLISTO_ADEPT("Callisto Adept", TaskTier.HARD, "Callisto", "Kill Callisto 50 times."),
    SKOTIZO_VETERAN("Skotizo Veteran", TaskTier.HARD, "Skotizo", "Kill Skotizo 10 times."),
    CHAOS_ELEMENTAL_ADEPT("Chaos Elemental Adept", TaskTier.HARD, "Chaos Elemental", "Kill the Chaos Elemental 50 times."),
    HOARDER("Hoarder", TaskTier.HARD, "Chaos Elemental", "Kill the Chaos Elemental without it unequipping any of your items."),
    THE_FLINCHER("The Flincher", TaskTier.HARD, "Chaos Elemental", "Kill the Chaos Elemental without taking any damage from it's attacks."),
    CHAOS_FANATIC_ADEPT("Chaos Fanatic Adept", TaskTier.HARD, "Chaos Fanatic", "Kill the Chaos Fanatic 50 times."),
    PRAYING_TO_THE_GODS("Praying to the Gods", TaskTier.HARD, "Chaos Fanatic", "Kill the Chaos Fanatic 10 times without drinking any potion which restores prayer or leaving the Wilderness."),
    CRAZY_ARCHAEOLOGIST_ADEPT("Crazy Archaeologist Adept", TaskTier.HARD, "Crazy archaeologist", "Kill the Crazy Archaeologist 50 times."),
    GROTESQUE_GUARDIANS_ADEPT("Grotesque Guardians Adept", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians 100 times."),
    DONT_LOOK_AT_THE_ECLIPSE("Don't Look at the Eclipse", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians without taking damage from Dusk's blinding attack."),
    PRISON_BREAK("Prison Break", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians without taking damage from Dusk's prison attack."),
    GRANITE_FOOTWORK("Granite Footwork", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians without taking damage from Dawn's rockfall attack."),
    HEAL_NO_MORE("Heal No More", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians without letting Dawn receive any healing from her orbs."),
    STATIC_AWARENESS("Static Awareness", TaskTier.HARD, "Grotesque Guardians", "Kill the Grotesque Guardians without being hit by any lightning attacks."),
    HESPORI_ADEPT("Hespori Adept", TaskTier.HARD, "Hespori", "Kill Hespori 10 times."),
    HESPORISNT("Hesporisn't", TaskTier.HARD, "Hespori", "Finish off Hespori with a special attack."),
    WEED_WHACKER("Weed Whacker", TaskTier.HARD, "Hespori", "Kill all of Hesporis flowers within 5 seconds."),
    KALPHITE_QUEEN_ADEPT("Kalphite Queen Adept", TaskTier.HARD, "Kalphite Queen", "Kill the Kalphite Queen 50 times."),
    CHITIN_PENETRATOR("Chitin Penetrator", TaskTier.HARD, "Kalphite Queen", "Kill the Kalphite Queen while her defence was last lowered by you."),
    WHO_IS_THE_KING_NOW("Who Is the King Now?", TaskTier.HARD, "King Black Dragon", "Kill The King Black Dragon 10 times in a privately rented instance without leaving the instance."),
    KRAKEN_ADEPT("Kraken Adept", TaskTier.HARD, "Kraken", "Kill the Kraken 100 times."),
    UNNECESSARY_OPTIMIZATION("Unnecessary Optimization", TaskTier.HARD, "Kraken", "Kill the Kraken after killing all four tentacles."),
    KRAKANT_HURT_ME("Krakan't Hurt Me", TaskTier.HARD, "Kraken", "Kill the Kraken 25 times in a privately rented instance without leaving the room."),
    WHY_ARE_YOU_RUNNING("Why Are You Running?", TaskTier.HARD, "Giant Mole", "Kill the Giant Mole without her burrowing more than 2 times."),
    WHACKAMOLE("Whack-a-Mole", TaskTier.HARD, "Giant Mole", "Kill the Giant Mole within 10 seconds of her resurfacing."),
    NIGHTMARE_CHAMPION("Nightmare Champion", TaskTier.HARD, "The Nightmare", "Kill The Nightmare once."),
    DAGANNOTH_PRIME_ADEPT("Dagannoth Prime Adept", TaskTier.HARD, "Dagannoth Prime", "Kill Dagannoth Prime 150 times."),
    DAGANNOTH_REX_ADEPT("Dagannoth Rex Adept", TaskTier.HARD, "Dagannoth Rex", "Kill Dagannoth Rex 150 times."),
    READY_TO_POUNCE("Ready to Pounce", TaskTier.HARD, "Sarachnis", "Kill Sarachnis without her using her range attack twice in a row."),
    INSPECT_REPELLENT("Inspect Repellent", TaskTier.HARD, "Sarachnis", "Kill Sarachnis without her dealing damage to anyone."),
    COMMANDER_ZILYANA_ADEPT("Commander Zilyana Adept", TaskTier.HARD, "Commander Zilyana", "Kill Commander Zilyana 50 times."),
    COMMANDER_SHOWDOWN("Commander Showdown", TaskTier.HARD, "Commander Zilyana", "Finish off Commander Zilyana while all of her bodyguards are dead."),
    SCORPIA_ADEPT("Scorpia Adept", TaskTier.HARD, "Scorpia", "Kill Scorpia 50 times."),
    I_CANT_REACH_THAT("I Can't Reach That", TaskTier.HARD, "Scorpia", "Kill Scorpia without taking any damage from her."),
    GUARDIANS_NO_MORE("Guardians No More", TaskTier.HARD, "Scorpia", "Kill Scorpia without killing her guardians."),
    ZULRAH_ADEPT("Zulrah Adept", TaskTier.HARD, "Zulrah", "Kill Zulrah 100 times."),
    DAGANNOTH_SUPREME_ADEPT("Dagannoth Supreme Adept", TaskTier.HARD, "Dagannoth Supreme", "Kill Dagannoth Supreme 150 times."),
    THEATRE_OF_BLOOD_SM_ADEPT("Theatre of Blood: SM Adept", TaskTier.HARD, "Theatre of Blood (Entry)", "Complete the Theatre of Blood: Entry Mode 1 time."),
    VENENATIS_ADEPT("Venenatis Adept", TaskTier.HARD, "Venenatis", "Kill Venenatis 50 times."),
    VETION_ADEPT("Vet'ion Adept", TaskTier.HARD, "Vet'ion", "Kill Vet'ion 50 times."),
    WHY_FLETCH("Why Fletch?", TaskTier.HARD, "Wintertodt", "Subdue the Wintertodt after earning 3000 or more points."),
    KRIL_TSUTSAROTH_ADEPT("K'ril Tsutsaroth Adept", TaskTier.HARD, "K'ril Tsutsaroth", "Kill K'ril Tsutsaroth 50 times."),
    YARR_NO_MORE("Yarr No More", TaskTier.HARD, "K'ril Tsutsaroth", "Receive kill-credit for K'ril Tsutsaroth without him using his special attack."),
    DEMONIC_SHOWDOWN("Demonic Showdown", TaskTier.HARD, "K'ril Tsutsaroth", "Finish off K'ril Tsutsaroth whilst all of his bodyguards are dead."),
    DEMONBANE_WEAPONRY_II("Demonbane Weaponry II", TaskTier.HARD, "K'ril Tsutsaroth", "Finish off K'ril Tsutsaroth with a demonbane weapon."),
    DRESS_LIKE_YOU_MEAN_IT("Dress Like You Mean It", TaskTier.HARD, "Tempoross", "Subdue Tempoross while wearing any variation of the angler outfit."),
    WHY_COOK("Why Cook?", TaskTier.HARD, "Tempoross", "Subdue Tempoross, getting rewarded with 10 reward permits from a single Tempoross fight."),
    ABYSSAL_VETERAN("Abyssal Veteran", TaskTier.ELITE, "Abyssal Sire", "Kill the Abyssal Sire 250 times."),
    RESPIRATORY_RUNNER("Respiratory Runner", TaskTier.ELITE, "Abyssal Sire", "Kill the Abyssal Sire after only stunning him once."),
    DEMONIC_REBOUND("Demonic Rebound", TaskTier.ELITE, "Abyssal Sire", "Use the Vengeance spell to reflect the damage from the Abyssal Sire's explosion back to him."),
    PERFECT_SIRE("Perfect Sire", TaskTier.ELITE, "Abyssal Sire", "Kill the Abyssal Sire without taking damage from the external tentacles, miasma pools, explosion or damage from the Abyssal Sire without praying the appropriate protection prayer."),
    KREEARRA_VETERAN("Kree'arra Veteran", TaskTier.ELITE, "Kree'arra", "Kill Kree'arra 250 times."),
    GENERAL_GRAARDOR_VETERAN("General Graardor Veteran", TaskTier.ELITE, "General Graardor", "Kill General Graardor 250 times."),
    OURG_FREEZER_II("Ourg Freezer II", TaskTier.ELITE, "General Graardor", "Kill General Graardor without him attacking any players."),
    REFLECTING_ON_THIS_ENCOUNTER("Reflecting on This Encounter", TaskTier.ELITE, "Basilisk Knight", "Kill a Basilisk Knight."),
    CALLISTO_VETERAN("Callisto Veteran", TaskTier.ELITE, "Callisto", "Kill Callisto 100 times."),
    DEMON_EVASION("Demon Evasion", TaskTier.ELITE, "Skotizo", "Kill Skotizo without taking any damage."),
    UP_FOR_THE_CHALLENGE("Up for the Challenge", TaskTier.ELITE, "Skotizo", "Kill Skotizo without equipping a demonbane weapon."),
    CERBERUS_VETERAN("Cerberus Veteran", TaskTier.ELITE, "Cerberus", "Kill Cerberus 150 times."),
    GHOST_BUSTER("Ghost Buster", TaskTier.ELITE, "Cerberus", "Kill Cerberus after successfully negating 6 or more attacks from Summoned Souls."),
    UNREQUIRED_ANTIFIRE("Unrequired Antifire", TaskTier.ELITE, "Cerberus", "Kill Cerberus without taking damage from any lava pools."),
    ANTIBITE_MECHANICS("Anti-Bite Mechanics", TaskTier.ELITE, "Cerberus", "Kill Cerberus without taking any melee damage."),
    CHAOS_ELEMENTAL_VETERAN("Chaos Elemental Veteran", TaskTier.ELITE, "Chaos Elemental", "Kill the Chaos Elemental 150 times."),
    CORPOREAL_BEAST_VETERAN("Corporeal Beast Veteran", TaskTier.ELITE, "Corporeal Beast", "Kill the Corporeal Beast 50 times."),
    HOT_ON_YOUR_FEET("Hot on Your Feet", TaskTier.ELITE, "Corporeal Beast", "Kill the Corporeal Beast without anyone killing the dark core or taking damage from the dark core."),
    FINDING_THE_WEAK_SPOT("Finding the Weak Spot", TaskTier.ELITE, "Corporeal Beast", "Finish off the Corporeal Beast with a Crystal Halberd special attack."),
    CHICKEN_KILLER("Chicken Killer", TaskTier.ELITE, "Corporeal Beast", "Kill the Corporeal Beast solo."),
    IF_GORILLAS_COULD_FLY("If Gorillas Could Fly", TaskTier.ELITE, "Demonic gorilla", "Kill a Demonic Gorilla."),
    HITTING_THEM_WHERE_IT_HURTS("Hitting Them Where It Hurts", TaskTier.ELITE, "Demonic gorilla", "Finish off a Demonic Gorilla with a demonbane weapon."),
    GALVEK_SPEEDTRIALIST("Galvek Speed-Trialist", TaskTier.ELITE, "Galvek", "Kill Galvek in less than 3 minutes."),
    GROTESQUE_GUARDIANS_VETERAN("Grotesque Guardians Veteran", TaskTier.ELITE, "Grotesque Guardians", "Kill the Grotesque Guardians 250 times."),
    DONE_BEFORE_DUSK("Done before Dusk", TaskTier.ELITE, "Grotesque Guardians", "Kill the Grotesque Guardians before Dusk uses his prison attack for a second time."),
    PERFECT_GROTESQUE_GUARDIANS("Perfect Grotesque Guardians", TaskTier.ELITE, "Grotesque Guardians", "Kill the Grotesque Guardians whilst completing the \"Don't look at the eclipse\", \"Prison Break\", \"Granite footwork\", \"Heal no more\", \"Static Awareness\" and \"Done before dusk\" tasks."),
    GROTESQUE_GUARDIANS_SPEEDTRIALIST("Grotesque Guardians Speed-Trialist", TaskTier.ELITE, "Grotesque Guardians", "Kill the Grotesque Guardians in less than 2 minutes."),
    FROM_DUSK("From Dusk...", TaskTier.ELITE, "Grotesque Guardians", "Kill the Grotesque Guardians 10 times without leaving the instance."),
    CORRUPTED_GAUNTLET_VETERAN("Corrupted Gauntlet Veteran", TaskTier.ELITE, "The Corrupted Gauntlet", "Complete the Corrupted Gauntlet 10 times."),
    TASK_3_2_1__MAGE("TASK 3, 2, 1 - Mage", TaskTier.ELITE, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef without taking damage off prayer."),
    GAUNTLET_ADEPT("Gauntlet Adept", TaskTier.ELITE, "The Gauntlet", "Complete the Gauntlet 10 times."),
    TASK_3_2_1__RANGE("TASK 3, 2, 1 - Range", TaskTier.ELITE, "The Gauntlet", "Kill the Crystalline Hunllef without taking damage off prayer."),
    EGNIOL_DIET("Egniol Diet", TaskTier.ELITE, "The Gauntlet", "Kill the Crystalline Hunllef without making an egniol potion within the Gauntlet."),
    CRYSTALLINE_WARRIOR("Crystalline Warrior", TaskTier.ELITE, "The Gauntlet", "Kill the Crystalline Hunllef with a full set of perfected armour equipped."),
    WOLF_PUNCHER("Wolf Puncher", TaskTier.ELITE, "The Gauntlet", "Kill the Crystalline Hunllef without making more than one attuned weapon."),
    GLOUGH_SPEEDTRIALIST("Glough Speed-Trialist", TaskTier.ELITE, "Glough", "Kill Glough in less than 2 minutes and 30 seconds."),
    PLANTBASED_DIET("Plant-Based Diet", TaskTier.ELITE, "Hespori", "Kill Hespori without losing any prayer points."),
    HESPORI_SPEEDTRIALIST("Hespori Speed-Trialist", TaskTier.ELITE, "Hespori", "Kill the Hespori in less than 48 seconds."),
    ALCHEMICAL_MASTER("Alchemical Master", TaskTier.ELITE, "Alchemical Hydra", "Kill the Alchemical Hydra 150 times."),
    FIGHT_CAVES_VETERAN("Fight Caves Veteran", TaskTier.ELITE, "Fight Caves", "Complete the Fight Caves once."),
    FACING_JAD_HEADON("Facing Jad Head-on", TaskTier.ELITE, "Fight Caves", "Complete the Fight Caves with only melee."),
    KALPHITE_QUEEN_VETERAN("Kalphite Queen Veteran", TaskTier.ELITE, "Kalphite Queen", "Kill the Kalphite Queen 250 times."),
    INSECT_DEFLECTION("Insect Deflection", TaskTier.ELITE, "Kalphite Queen", "Kill the Kalphite Queen by using the Vengeance spell as the finishing blow."),
    PRAYER_SMASHER("Prayer Smasher", TaskTier.ELITE, "Kalphite Queen", "Kill the Kalphite Queen using only the Verac's Flail as a weapon."),
    TENTACLES("Ten-tacles", TaskTier.ELITE, "Kraken", "Kill the Kraken 50 times in a privately rented instance without leaving the room."),
    MIMIC_ADEPT("Mimic Adept", TaskTier.ELITE, "Mimic", "Kill the Mimic once."),
    HARD_HITTER("Hard Hitter", TaskTier.ELITE, "Giant Mole", "Kill the Giant Mole with 4 or less instances of damage."),
    NIGHTMARE_ADEPT("Nightmare Adept", TaskTier.ELITE, "The Nightmare", "Kill The Nightmare 100 times."),
    EXPLOSION("Explosion!", TaskTier.ELITE, "The Nightmare", "Kill two Husks at the same time."),
    SLEEP_TIGHT("Sleep Tight", TaskTier.ELITE, "The Nightmare", "Kill the Nightmare solo."),
    NIGHTMARE_5SCALE_SPEEDTRIALIST("Nightmare (5-Scale) Speed-Trialist", TaskTier.ELITE, "The Nightmare", "Defeat the Nightmare (5-scale) in less than 5 minutes."),
    DEATH_TO_THE_SEER_KING("Death to the Seer King", TaskTier.ELITE, "Dagannoth Prime", "Kill Dagannoth Prime whilst under attack by Dagannoth Supreme and Dagannoth Rex."),
    FROM_ONE_KING_TO_ANOTHER("From One King to Another", TaskTier.ELITE, "Dagannoth Prime", "Kill Prime using a Rune Thrownaxe special attack, bounced off Dagannoth Rex."),
    DEATH_TO_THE_WARRIOR_KING("Death to the Warrior King", TaskTier.ELITE, "Dagannoth Rex", "Kill Dagannoth Rex whilst under attack by Dagannoth Supreme and Dagannoth Prime."),
    TOPPLING_THE_DIARCHY("Toppling the Diarchy", TaskTier.ELITE, "Dagannoth Rex", "Kill Dagannoth Rex and one other Dagannoth king at the exact same time."),
    COMMANDER_ZILYANA_VETERAN("Commander Zilyana Veteran", TaskTier.ELITE, "Commander Zilyana", "Kill Commander Zilyana 250 times."),
    REMINISCE("Reminisce", TaskTier.ELITE, "Commander Zilyana", "Kill Commander Zilyana in a privately rented instance with melee only."),
    SCORPIA_VETERAN("Scorpia Veteran", TaskTier.ELITE, "Scorpia", "Kill Scorpia 150 times."),
    FRAGMENT_OF_SEREN_SPEEDTRIALIST("Fragment of Seren Speed-Trialist", TaskTier.ELITE, "Fragment of Seren", "Kill The Fragment of Seren in less than 4 minutes."),
    ZULRAH_VETERAN("Zulrah Veteran", TaskTier.ELITE, "Zulrah", "Kill Zulrah 150 times."),
    SNAKE_REBOUND("Snake Rebound", TaskTier.ELITE, "Zulrah", "Kill Zulrah by using the Vengeance spell as the finishing blow."),
    SNAKE_SNAKE_SNAAAAAAKE("Snake. Snake!? Snaaaaaake!", TaskTier.ELITE, "Zulrah", "Kill 3 Snakelings simultaneously."),
    ZULRAH_SPEEDTRIALIST("Zulrah Speed-Trialist", TaskTier.ELITE, "Zulrah", "Kill Zulrah in less than 1 minute 20 seconds, without a slayer task."),
    DEATH_TO_THE_ARCHER_KING("Death to the Archer King", TaskTier.ELITE, "Dagannoth Supreme", "Kill Dagannoth Supreme whilst under attack by Dagannoth Prime and Dagannoth Rex."),
    RAPID_SUCCESSION("Rapid Succession", TaskTier.ELITE, "Dagannoth Supreme", "Kill all three Dagannoth Kings within 9 seconds of the first one."),
    ANTICOAGULANTS("Anticoagulants", TaskTier.ELITE, "Theatre of Blood (Entry)", "Defeat the Maiden of Sugadinti in the Theatre of Blood: Entry Mode without letting any bloodspawn live for longer than 10 seconds."),
    APPROPRIATE_TOOLS("Appropriate Tools", TaskTier.ELITE, "Theatre of Blood (Entry)", "Defeat the Pestilent Bloat in the Theatre of Blood: Entry Mode with everyone having a salve amulet equipped."),
    THEY_WONT_EXPECT_THIS("They Won't Expect This", TaskTier.ELITE, "Theatre of Blood (Entry)", "In the Theatre of Blood: Entry Mode, enter the Pestilent Bloat room from the opposite side."),
    CHALLY_TIME("Chally Time", TaskTier.ELITE, "Theatre of Blood (Entry)", "Defeat the Pestilent Bloat in the Theatre of Blood: Entry Mode by using a crystal halberd special attack as your final attack."),
    NYLOCAS_ON_THE_ROCKS("Nylocas, On the Rocks", TaskTier.ELITE, "Theatre of Blood (Entry)", "In the Theatre of Blood: Entry Mode, freeze any 4 Nylocas with a single Ice Barrage spell."),
    JUST_TO_BE_SAFE("Just To Be Safe", TaskTier.ELITE, "Theatre of Blood (Entry)", "Defeat Sotetseg in the Theatre of Blood: Entry Mode after having split the big ball with your entire team. This must be done with a group size of at least 2."),
    DONT_LOOK_AT_ME("Don't Look at Me!", TaskTier.ELITE, "Theatre of Blood (Entry)", "Kill Xarpus in the Theatre of Blood: Entry Mode without him reflecting any damage to anyone."),
    NOPILLAR("No-Pillar", TaskTier.ELITE, "Theatre of Blood (Entry)", "Survive Verzik Vitur's pillar phase in the Theatre of Blood: Entry Mode without losing a single pillar."),
    ATTACK_STEP_WAIT("Attack, Step, Wait", TaskTier.ELITE, "Theatre of Blood (Entry)", "Survive Verzik Vitur's second phase in the Theatre of Blood: Entry Mode without anyone getting bounced by Verzik."),
    PASS_IT_ON("Pass It On", TaskTier.ELITE, "Theatre of Blood (Entry)", "In the Theatre of Blood: Entry Mode, successfully pass on the green ball to a team mate."),
    THEATRE_OF_BLOOD_VETERAN("Theatre of Blood Veteran", TaskTier.ELITE, "Theatre of Blood", "Complete the Theatre of Blood 75 times."),
    THERMONUCLEAR_ADEPT("Thermonuclear Adept", TaskTier.ELITE, "Thermonuclear smoke devil", "Kill the Thermonuclear Smoke Devil 100 times."),
    HAZARD_PREVENTION("Hazard Prevention", TaskTier.ELITE, "Thermonuclear smoke devil", "Kill the Thermonuclear Smoke Devil without it hitting anyone."),
    SPECD_OUT("Spec'd Out", TaskTier.ELITE, "Thermonuclear smoke devil", "Kill the Thermonuclear Smoke Devil using only special attacks."),
    VENENATIS_VETERAN("Venenatis Veteran", TaskTier.ELITE, "Venenatis", "Kill Venenatis 100 times."),
    VETERAN("Vet'eran", TaskTier.ELITE, "Vet'ion", "Kill Vet'ion 100 times."),
    VORKATH_VETERAN("Vorkath Veteran", TaskTier.ELITE, "Vorkath", "Kill Vorkath 50 times."),
    STICK_EM_WITH_THE_POINTY_END("Stick 'em With the Pointy End", TaskTier.ELITE, "Vorkath", "Kill Vorkath using melee weapons only."),
    ZOMBIE_DESTROYER("Zombie Destroyer", TaskTier.ELITE, "Vorkath", "Kill Vorkath's zombified spawn without using crumble undead."),
    DUST_SEEKER("Dust Seeker", TaskTier.ELITE, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric Challenge mode raid in the target time."),
    CHAMBERS_OF_XERIC_VETERAN("Chambers of Xeric Veteran", TaskTier.ELITE, "Chambers of Xeric", "Complete the Chambers of Xeric 75 times."),
    PERFECTLY_BALANCED("Perfectly Balanced", TaskTier.ELITE, "Chambers of Xeric", "Kill the Vanguards without them resetting their health."),
    TOGETHER_WELL_FALL("Together We'll Fall", TaskTier.ELITE, "Chambers of Xeric", "Kill the Vanguards within 10 seconds of the first one dying."),
    REDEMPTION_ENTHUSIAST("Redemption Enthusiast", TaskTier.ELITE, "Chambers of Xeric", "Kill the Abyssal Portal without forcing Vespula to land."),
    MUTTADIET("Mutta-diet", TaskTier.ELITE, "Chambers of Xeric", "Kill the Muttadile without letting her or her baby recover hitpoints from the meat tree."),
    DANCING_WITH_STATUES("Dancing with Statues", TaskTier.ELITE, "Chambers of Xeric", "Receive kill-credit for a Stone Guardian without taking damage from falling rocks."),
    UNDYING_RAID_TEAM("Undying Raid Team", TaskTier.ELITE, "Chambers of Xeric", "Complete a Chambers of Xeric raid without anyone dying."),
    SHAYZIEN_SPECIALIST("Shayzien Specialist", TaskTier.ELITE, "Chambers of Xeric", "Receive kill-credit for a Lizardman Shaman without taking damage from any shamans in the room."),
    CRYO_NO_MORE("Cryo No More", TaskTier.ELITE, "Chambers of Xeric", "Receive kill-credit for the Ice Demon without taking any damage."),
    BLIZZARD_DODGER("Blizzard Dodger", TaskTier.ELITE, "Chambers of Xeric", "Receive kill-credit for the Ice Demon without activating the Protect from Range prayer."),
    KILL_IT_WITH_FIRE("Kill It with Fire", TaskTier.ELITE, "Chambers of Xeric", "Finish off the Ice Demon with a fire spell."),
    ZALCANO_VETERAN("Zalcano Veteran", TaskTier.ELITE, "Zalcano", "Kill Zalcano 150 times."),
    PERFECT_ZALCANO("Perfect Zalcano", TaskTier.ELITE, "Zalcano", "Kill Zalcano 5 times in a row without leaving or getting hit by the following: Falling rocks, rock explosions, Zalcano powering up, or standing in a red symbol."),
    TEAM_PLAYER("Team Player", TaskTier.ELITE, "Zalcano", "Receive imbued tephra from a golem."),
    THE_SPURNED_HERO("The Spurned Hero", TaskTier.ELITE, "Zalcano", "Kill Zalcano as the player who has dealt the most damage to her."),
    KRIL_TSUTSAROTH_VETERAN("K'ril Tsutsaroth Veteran", TaskTier.ELITE, "K'ril Tsutsaroth", "Kill K'ril Tsutsaroth 250 times."),
    DEMONIC_DEFENCE("Demonic Defence", TaskTier.ELITE, "K'ril Tsutsaroth", "Kill K'ril Tsutsaroth in a privately rented instance without taking any of his melee hits."),
    THE_BANE_OF_DEMONS("The Bane of Demons", TaskTier.ELITE, "K'ril Tsutsaroth", "Defeat K'ril Tsutsaroth in a privately rented instance using only demonbane spells."),
    HALFWAY_THERE("Half-Way There", TaskTier.ELITE, "Inferno", "Kill a Jal-Zek within the Inferno."),
    A_NEAR_MISS("A Near Miss!", TaskTier.ELITE, "Fight Caves", "Complete the Fight Caves after surviving a hit from TzTok-Jad without praying."),
    THE_II_JAD_CHALLENGE("The II Jad Challenge", TaskTier.ELITE, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's second challenge."),
    TZHAARKETRAKS_SPEEDTRIALIST("TzHaar-Ket-Rak's Speed-Trialist", TaskTier.ELITE, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's first challenge in less than 45 seconds."),
    FACING_JAD_HEADON_III("Facing Jad Head-on III", TaskTier.ELITE, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's second challenge with only melee."),
    PHOSANIS_CHAMPION("Phosani's Champion", TaskTier.ELITE, "Phosani's Nightmare", "Kill Phosani's Nightmare once."),
    COLLATERAL_DAMAGE("Collateral Damage", TaskTier.MASTER, "Kree'arra", "Kill Kree'arra in a private instance without ever attacking him directly."),
    SWOOP_NO_MORE("Swoop No More", TaskTier.MASTER, "Kree'arra", "Kill Kree'arra in a private instance without taking any melee damage from the boss or his bodyguards."),
    PRECISE_POSITIONING("Precise Positioning", TaskTier.MASTER, "Skotizo", "Kill Skotizo with the final source of damage being a Chinchompa explosion."),
    CERBERUS_MASTER("Cerberus Master", TaskTier.MASTER, "Cerberus", "Kill Cerberus 250 times."),
    AROOO_NO_MORE("Arooo No More", TaskTier.MASTER, "Cerberus", "Kill Cerberus without any of the Summoned Souls being spawned."),
    CORPOREAL_BEAST_MASTER("Corporeal Beast Master", TaskTier.MASTER, "Corporeal Beast", "Kill the Corporeal Beast 150 times."),
    PERFECT_GROTESQUE_GUARDIANS_II("Perfect Grotesque Guardians II", TaskTier.MASTER, "Grotesque Guardians", "Kill the Grotesque Guardians 5 times in a row whilst completing the Perfect Grotesque Guardians task every time."),
    GROTESQUE_GUARDIANS_SPEEDCHASER("Grotesque Guardians Speed-Chaser", TaskTier.MASTER, "Grotesque Guardians", "Kill the Grotesque Guardians in less than 1:40 minutes."),
    _TIL_DAWN("... 'til Dawn", TaskTier.MASTER, "Grotesque Guardians", "Kill the Grotesque Guardians 20 times without leaving the instance."),
    CORRUPTED_GAUNTLET_MASTER("Corrupted Gauntlet Master", TaskTier.MASTER, "The Corrupted Gauntlet", "Complete the Corrupted Gauntlet 50 times."),
    PERFECT_CORRUPTED_HUNLLEF("Perfect Corrupted Hunllef", TaskTier.MASTER, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef without taking damage from: Tornadoes, Damaging Floor or Stomp Attacks. Also, do not take damage off prayer and do not attack the Corrupted Hunleff with the wrong weapon."),
    DEFENCE_DOESNT_MATTER_II("Defence Doesn't Matter II", TaskTier.MASTER, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef without making any armour within the Corrupted Gauntlet."),
    CORRUPTED_WARRIOR("Corrupted Warrior", TaskTier.MASTER, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef with a full set of perfected corrupted armour equipped."),
    CORRUPTED_GAUNTLET_SPEEDCHASER("Corrupted Gauntlet Speed-Chaser", TaskTier.MASTER, "The Corrupted Gauntlet", "Complete a Corrupted Gauntlet in less than 7 minutes and 30 seconds."),
    GAUNTLET_MASTER("Gauntlet Master", TaskTier.MASTER, "The Gauntlet", "Complete the Gauntlet 100 times."),
    PERFECT_CRYSTALLINE_HUNLLEF("Perfect Crystalline Hunllef", TaskTier.MASTER, "The Gauntlet", "Kill the Crystalline Hunllef without taking damage from: Tornadoes, Damaging Floor or Stomp Attacks. Also, do not take damage off prayer and do not attack the Crystalline Hunleff with the wrong weapon."),
    DEFENCE_DOESNT_MATTER("Defence Doesn't Matter", TaskTier.MASTER, "The Gauntlet", "Kill the Crystalline Hunllef without making any armour within the Gauntlet."),
    GAUNTLET_SPEEDCHASER("Gauntlet Speed-Chaser", TaskTier.MASTER, "The Gauntlet", "Complete the Gauntlet in less than 5 minutes."),
    HESPORI_SPEEDCHASER("Hespori Speed-Chaser", TaskTier.MASTER, "Hespori", "Kill the Hespori in less than 36 seconds."),
    ALCHEMICAL_GRANDMASTER("Alchemical Grandmaster", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra 250 times."),
    UNREQUIRED_ANTIPOISONS("Unrequired Antipoisons", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without being hit by the acid pool attack."),
    LIGHTNING_LURE("Lightning Lure", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without being hit by the lightning attack."),
    DONT_FLAME_ME("Don't Flame Me", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without being hit by the flame wall attack."),
    MIXING_CORRECTLY("Mixing Correctly", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without empowering it."),
    THE_FLAME_SKIPPER("The Flame Skipper", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without letting it spawn a flame wall attack."),
    ALCLEANICAL_HYDRA("Alcleanical Hydra", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra without taking any damage."),
    ALCHEMICAL_SPEEDCHASER("Alchemical Speed-Chaser", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra in less than 1 minute 45 seconds."),
    WORKING_OVERTIME("Working Overtime", TaskTier.MASTER, "Alchemical Hydra", "Kill the Alchemical Hydra 15 times without leaving the room."),
    FIGHT_CAVES_MASTER("Fight Caves Master", TaskTier.MASTER, "Fight Caves", "Complete the Fight Caves 10 times."),
    DENYING_THE_HEALERS("Denying the Healers", TaskTier.MASTER, "Fight Caves", "Complete the Fight caves without letting any of the Yt-MejKot heal."),
    YOU_DIDNT_SAY_ANYTHING_ABOUT_A_BAT("You Didn't Say Anything About a Bat", TaskTier.MASTER, "Fight Caves", "Complete the Fight Caves without being attacked by a Tz-Kih."),
    FIGHT_CAVES_SPEEDCHASER("Fight Caves Speed-Chaser", TaskTier.MASTER, "Fight Caves", "Complete the Fight Caves in less than 30 minutes."),
    ONE_HUNDRED_TENTACLES("One Hundred Tentacles", TaskTier.MASTER, "Kraken", "Kill the Kraken 100 times in a private instance without leaving the room."),
    NIGHTMARE_VETERAN("Nightmare Veteran", TaskTier.MASTER, "The Nightmare", "Kill The Nightmare 250 times."),
    PERFECT_NIGHTMARE("Perfect Nightmare", TaskTier.MASTER, "The Nightmare", "Kill the Nightmare without any player taking damage from the following attacks: Nightmare rifts, an un-cured parasite explosion, Corpse flowers or the Nightmare's Surge. Also, no player can take damage off prayer or have their attacks slowed by the Nightmare spores."),
    NIGHTMARE_SOLO_SPEEDTRIALIST("Nightmare (Solo) Speed-Trialist", TaskTier.MASTER, "The Nightmare", "Defeat the Nightmare (Solo) in less than 23 minutes."),
    NIGHTMARE_SOLO_SPEEDCHASER("Nightmare (Solo) Speed-Chaser", TaskTier.MASTER, "The Nightmare", "Defeat the Nightmare (Solo) in less than 19 minutes."),
    NIGHTMARE_5SCALE_SPEEDCHASER("Nightmare (5-Scale) Speed-Chaser", TaskTier.MASTER, "The Nightmare", "Defeat the Nightmare (5-scale) in less than 4 minutes."),
    MOVING_COLLATERAL("Moving Collateral", TaskTier.MASTER, "Commander Zilyana", "Kill Commander Zilyana in a private instance without attacking her directly."),
    ZULRAH_MASTER("Zulrah Master", TaskTier.MASTER, "Zulrah", "Kill Zulrah 250 times."),
    PERFECT_ZULRAH("Perfect Zulrah", TaskTier.MASTER, "Zulrah", "Kill Zulrah whilst taking no damage from the following: Snakelings, Venom Clouds, Zulrah's Green or Crimson phase."),
    ZULRAH_SPEEDCHASER("Zulrah Speed-Chaser", TaskTier.MASTER, "Zulrah", "Kill Zulrah in less than 1 minute, without a slayer task."),
    CANT_DRAIN_THIS("Can't Drain This", TaskTier.MASTER, "Theatre of Blood", "Kill The Maiden of Sugadinti without anyone in the team losing any prayer points."),
    PERFECT_MAIDEN("Perfect Maiden", TaskTier.MASTER, "Theatre of Blood", "Kill The Maiden of Sugadinti without anyone in the team taking damage from the following sources: Blood Spawn projectiles and Blood Spawn trails. Also, without taking damage off prayer and without letting any of the Nylocas Matomenos heal The Maiden."),
    TWODOWN("Two-Down", TaskTier.MASTER, "Theatre of Blood", "Kill the Pestilent Bloat before he shuts down for the third time."),
    PERFECT_BLOAT("Perfect Bloat", TaskTier.MASTER, "Theatre of Blood", "Kill the Pestilent Bloat without anyone in the team taking damage from the following sources: Pestilent flies, Falling body parts or The Pestilent Bloats stomp attack."),
    PERFECT_NYLOCAS("Perfect Nylocas", TaskTier.MASTER, "Theatre of Blood", "Kill the Nylocas Vasilias without anyone in the team attacking any Nylocas with the wrong attack style, without letting a pillar collapse and without getting hit by any of the Nylocas Vasilias attacks whilst off prayer."),
    A_TIMELY_SNACK("A Timely Snack", TaskTier.MASTER, "Theatre of Blood", "Kill Sotetseg after surviving at least 3 ball attacks without sharing the damage and without anyone dying throughout the fight."),
    PERFECT_SOTESTEG("Perfect Sotesteg", TaskTier.MASTER, "Theatre of Blood", "Kill Sotetseg without anyone in the team stepping on the wrong tile in the maze, without getting hit by the tornado and without taking any damage from Sotetseg's attacks whilst off prayer."),
    CAN_YOU_DANCE("Can You Dance?", TaskTier.MASTER, "Theatre of Blood", "Kill Xarpus without anyone in the team using a ranged or magic weapon."),
    PERFECT_XARPUS("Perfect Xarpus", TaskTier.MASTER, "Theatre of Blood", "Kill Xarpus without anyone in the team taking any damage from Xarpus' attacks and without letting an exhumed heal Xarpus more than twice."),
    POP_IT("Pop It", TaskTier.MASTER, "Theatre of Blood", "Kill Verzik without any Nylocas being frozen and without anyone taking damage from the Nylocas."),
    PERFECT_VERZIK("Perfect Verzik", TaskTier.MASTER, "Theatre of Blood", "Defeat Verzik Vitur without anyone in the team taking damage from Verzik Vitur's attacks other than her spider form's correctly prayed against regular magical and ranged attacks."),
    BACK_IN_MY_DAY("Back in My Day...", TaskTier.MASTER, "Theatre of Blood", "Complete the Theatre of Blood without any member of the team equipping a Scythe of Vitur."),
    THEATRE_TRIO_SPEEDCHASER("Theatre (Trio) Speed-Chaser", TaskTier.MASTER, "Theatre of Blood", "Complete the Theatre of Blood (Trio) in less than 20 minutes."),
    THEATRE_4SCALE_SPEEDCHASER("Theatre (4-Scale) Speed-Chaser", TaskTier.MASTER, "Theatre of Blood", "Complete the Theatre of Blood (4-scale) in less than 17 minutes."),
    THEATRE_5SCALE_SPEEDCHASER("Theatre (5-Scale) Speed-Chaser", TaskTier.MASTER, "Theatre of Blood", "Complete the Theatre of Blood (5-scale) in less than 16 minutes."),
    THEATRE_OF_BLOOD_MASTER("Theatre of Blood Master", TaskTier.MASTER, "Theatre of Blood", "Complete the Theatre of Blood 150 times."),
    VORKATH_MASTER("Vorkath Master", TaskTier.MASTER, "Vorkath", "Kill Vorkath 250 times."),
    THE_WALK("The Walk", TaskTier.MASTER, "Vorkath", "Hit Vorkath 12 times during the acid special without getting hit by his rapid fire or the acid pools."),
    DODGING_THE_DRAGON("Dodging the Dragon", TaskTier.MASTER, "Vorkath", "Kill Vorkath 5 times without taking any damage from his special attacks and without leaving his area."),
    VORKATH_SPEEDCHASER("Vorkath Speed-Chaser", TaskTier.MASTER, "Vorkath", "Kill Vorkath in less than 1 minute and 15 seconds."),
    EXTENDED_ENCOUNTER("Extended Encounter", TaskTier.MASTER, "Vorkath", "Kill Vorkath 10 times without leaving his area."),
    CHAMBERS_OF_XERIC_CM_MASTER("Chambers of Xeric: CM Master", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete the Chambers of Xeric: Challenge Mode 50 times."),
    IMMORTAL_RAID_TEAM("Immortal Raid Team", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge mode raid without anyone dying."),
    IMMORTAL_RAIDER("Immortal Raider", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric Challenge mode (Solo) raid without dying."),
    CHAMBERS_OF_XERIC_CM_SOLO_SPEEDCHASER("Chambers of Xeric: CM (Solo) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (Solo) in less than 45 minutes."),
    CHAMBERS_OF_XERIC_CM_5SCALE_SPEEDCHASER("Chambers of Xeric: CM (5-Scale) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (5-scale) in less than 30 minutes."),
    CHAMBERS_OF_XERIC_CM_TRIO_SPEEDCHASER("Chambers of Xeric: CM (Trio) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (Trio) in less than 35 minutes."),
    CHAMBERS_OF_XERIC_MASTER("Chambers of Xeric Master", TaskTier.MASTER, "Chambers of Xeric", "Complete the Chambers of Xeric 150 times."),
    NO_TIME_FOR_DEATH("No Time for Death", TaskTier.MASTER, "Chambers of Xeric", "Clear the Tightrope room without killing any Deathly Mages or Deathly Rangers."),
    PUTTING_IT_OLM_ON_THE_LINE("Putting It Olm on the Line", TaskTier.MASTER, "Chambers of Xeric", "Complete a Chambers of Xeric solo raid with more than 40,000 points."),
    A_NOT_SO_SPECIAL_LIZARD("A Not So Special Lizard", TaskTier.MASTER, "Chambers of Xeric", "Kill the Great Olm in a solo raid without letting him use any of the following special attacks in his second to last phase: Crystal Burst, Lightning Walls, Teleportation Portals or left-hand autohealing."),
    STOP_DROP_AND_ROLL("Stop Drop and Roll", TaskTier.MASTER, "Chambers of Xeric", "Kill Vasa Nistirio before he performs his teleport attack for the second time."),
    ANVIL_NO_MORE("Anvil No More", TaskTier.MASTER, "Chambers of Xeric", "Kill Tekton before he returns to his anvil for a second time after the fight begins."),
    UNDYING_RAIDER("Undying Raider", TaskTier.MASTER, "Chambers of Xeric", "Complete a Chambers of Xeric solo raid without dying."),
    PLAYING_WITH_LASERS("Playing with Lasers", TaskTier.MASTER, "Chambers of Xeric", "Clear the Crystal Crabs room without wasting an orb after the first crystal has been activated."),
    PERFECT_OLM_SOLO("Perfect Olm (Solo)", TaskTier.MASTER, "Chambers of Xeric", "Kill the Great Olm in a solo raid without taking damage from any of the following: Teleport portals, Fire Walls, Healing pools, Crystal Bombs, Crystal Burst or Prayer Orbs. You also cannot let his claws regenerate or take damage from the same acid pool back to back."),
    PERFECT_OLM_TRIO("Perfect Olm (Trio)", TaskTier.MASTER, "Chambers of Xeric", "Kill the Great Olm in a trio raid without any team member taking damage from any of the following: Teleport portals, Fire Walls, Healing pools, Crystal Bombs, Crystal Burst or Prayer Orbs. You also cannot let his claws regenerate or take damage from the same acid pool back to back."),
    BLIND_SPOT("Blind Spot", TaskTier.MASTER, "Chambers of Xeric", "Kill Tekton without taking any damage."),
    CHAMBERS_OF_XERIC_SOLO_SPEEDCHASER("Chambers of Xeric (Solo) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (Solo) in less than 21 minutes."),
    CHAMBERS_OF_XERIC_TRIO_SPEEDCHASER("Chambers of Xeric (Trio) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (Trio) in less than 16 minutes and 30 seconds."),
    CHAMBERS_OF_XERIC_5SCALE_SPEEDCHASER("Chambers of Xeric (5-Scale) Speed-Chaser", TaskTier.MASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (5-scale) in less than 15 minutes."),
    NIBBLERS_BEGONE("Nibblers, Begone!", TaskTier.MASTER, "Inferno", "Kill Tzkal-Zuk without letting a pillar fall before wave 67."),
    THE_IV_JAD_CHALLENGE("The IV Jad Challenge", TaskTier.MASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's fourth challenge."),
    TZHAARKETRAKS_SPEEDCHASER("TzHaar-Ket-Rak's Speed-Chaser", TaskTier.MASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's third challenge in less than 3 minutes."),
    FACING_JAD_HEADON_IV("Facing Jad Head-on IV", TaskTier.MASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's fourth challenge with only melee."),
    SUPPLIES_WHO_NEEDS_EM("Supplies? Who Needs 'em?", TaskTier.MASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's third challenge without having anything in your inventory."),
    MULTISTYLE_SPECIALIST("Multi-Style Specialist", TaskTier.MASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's third challenge while using a different attack style for each JalTok-Jad."),
    HARD_MODE_COMPLETED_IT("Hard Mode? Completed It", TaskTier.MASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode within the challenge time."),
    THEATRE_OF_BLOOD_SM_SPEEDCHASER("Theatre of Blood: SM Speed-Chaser", TaskTier.MASTER, "Theatre of Blood (Entry)", "Complete the Theatre of Blood: Entry Mode in less than 17 minutes."),
    PHOSANIS_ADEPT("Phosani's Adept", TaskTier.MASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare 25 times."),
    PHOSANIS_SPEEDCHASER("Phosani's Speedchaser", TaskTier.MASTER, "Phosani's Nightmare", "Defeat Phosani's Nighmare within 8 minutes."),
    CRUSH_HOUR("Crush Hour", TaskTier.MASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare while killing every parasite and husk in one hit."),
    I_WOULD_SIMPLY_REACT("I Would Simply React", TaskTier.MASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare without allowing your prayer to be disabled."),
    DREAMLAND_EXPRESS("Dreamland Express", TaskTier.MASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare without a sleepwalker reaching her during her desperation phase."),
    THE_WORST_RANGED_WEAPON("The Worst Ranged Weapon", TaskTier.GRANDMASTER, "Kree'arra", "Kill Kree'arra by only dealing damage to him with a salamander."),
    FEATHER_HUNTER("Feather Hunter", TaskTier.GRANDMASTER, "Kree'arra", "Kill Kree'arra 30 times in a privately rented instance without leaving the room."),
    DEFENCE_MATTERS("Defence Matters", TaskTier.GRANDMASTER, "General Graardor", "Kill General Graardor 2 times consecutively in a privately rented instance without taking any damage from his bodyguards."),
    KEEP_AWAY("Keep Away", TaskTier.GRANDMASTER, "General Graardor", "Kill General Graardor in a privately rented instance without taking any damage from the boss or bodyguards."),
    OURG_KILLER("Ourg Killer", TaskTier.GRANDMASTER, "General Graardor", "Kill General Graardor 15 times in a privately rented instance without leaving the room."),
    GROTESQUE_GUARDIANS_SPEEDRUNNER("Grotesque Guardians Speed-Runner", TaskTier.GRANDMASTER, "Grotesque Guardians", "Kill the Grotesque Guardians in less than 1:20 minutes."),
    CORRUPTED_GAUNTLET_GRANDMASTER("Corrupted Gauntlet Grandmaster", TaskTier.GRANDMASTER, "The Corrupted Gauntlet", "Complete the Corrupted Gauntlet 150 times."),
    EGNIOL_DIET_II("Egniol Diet II", TaskTier.GRANDMASTER, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef without making an egniol potion within the Corrupted Gauntlet."),
    WOLF_PUNCHER_II("Wolf Puncher II", TaskTier.GRANDMASTER, "The Corrupted Gauntlet", "Kill the Corrupted Hunllef without making more than one attuned weapon."),
    CORRUPTED_GAUNTLET_SPEEDRUNNER("Corrupted Gauntlet Speed-Runner", TaskTier.GRANDMASTER, "The Corrupted Gauntlet", "Complete a Corrupted Gauntlet in less than 6 minutes and 30 seconds."),
    GAUNTLET_SPEEDRUNNER("Gauntlet Speed-Runner", TaskTier.GRANDMASTER, "The Gauntlet", "Complete the Gauntlet in less than 4 minutes."),
    NO_PRESSURE("No Pressure", TaskTier.GRANDMASTER, "Alchemical Hydra", "Kill the Alchemical Hydra using only Dharok's Greataxe as a weapon whilst having no more than 10 Hitpoints throughout the entire fight."),
    ALCHEMICAL_SPEEDRUNNER("Alchemical Speed-Runner", TaskTier.GRANDMASTER, "Alchemical Hydra", "Kill the Alchemical Hydra in less than 1 minute 20 seconds."),
    DENYING_THE_HEALERS_II("Denying the Healers II", TaskTier.GRANDMASTER, "Fight Caves", "Complete the Fight Caves without TzTok-Jad being healed by a Yt-HurKot."),
    NO_TIME_FOR_A_DRINK("No Time for a Drink", TaskTier.GRANDMASTER, "Fight Caves", "Complete the Fight Caves without losing any prayer points."),
    FIGHT_CAVES_SPEEDRUNNER("Fight Caves Speed-Runner", TaskTier.GRANDMASTER, "Fight Caves", "Complete the Fight Caves in less than 26 minutes and 30 seconds."),
    TERRIBLE_PARENT("Terrible Parent", TaskTier.GRANDMASTER, "The Nightmare", "Kill the Nightmare solo without the Parasites healing the boss for more than 100 health."),
    A_LONG_TRIP("A Long Trip", TaskTier.GRANDMASTER, "The Nightmare", "Kill the Nightmare without any player losing any prayer points."),
    NIGHTMARE_SOLO_SPEEDRUNNER("Nightmare (Solo) Speed-Runner", TaskTier.GRANDMASTER, "The Nightmare", "Defeat the Nightmare (Solo) in less than 16 minutes."),
    NIGHTMARE_5SCALE_SPEEDRUNNER("Nightmare (5-Scale) Speed-Runner", TaskTier.GRANDMASTER, "The Nightmare", "Defeat the Nightmare (5-scale) in less than 3:30 minutes."),
    ANIMAL_WHISPERER("Animal Whisperer", TaskTier.GRANDMASTER, "Commander Zilyana", "Kill Commander Zilyana in a privately rented instance without taking any damage from the boss or bodyguards."),
    PEACH_CONJURER("Peach Conjurer", TaskTier.GRANDMASTER, "Commander Zilyana", "Kill Commander Zilyana 50 times in a privately rented instance without leaving the room."),
    ZULRAH_SPEEDRUNNER("Zulrah Speed-Runner", TaskTier.GRANDMASTER, "Zulrah", "Kill Zulrah in less than 54 seconds, without a slayer task."),
    THEATRE_OF_BLOOD_GRANDMASTER("Theatre of Blood Grandmaster", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood 250 times."),
    PERFECT_THEATRE("Perfect Theatre", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood without anyone dying through any means and whilst everyone in the team completes the following Combat Achievement tasks in a single run: \"Perfect Maiden\", \"Perfect Bloat\", \"Perfect Nylocas\", \"Perfect Sotetseg\", \"Perfect Xarpus\" and \"Perfect Verzik\"."),
    MORYTANIA_ONLY("Morytania Only", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood without any member of the team equipping a non-barrows weapon (except Dawnbringer)."),
    THEATRE_DUO_SPEEDRUNNER("Theatre (Duo) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood (Duo) in less than 26 minutes."),
    THEATRE_TRIO_SPEEDRUNNER("Theatre (Trio) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood (Trio) in less than 17 minutes and 30 seconds."),
    THEATRE_4SCALE_SPEEDRUNNER("Theatre (4-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood (4-scale) in less than 15 minutes."),
    THEATRE_5SCALE_SPEEDRUNNER("Theatre (5-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood", "Complete the Theatre of Blood (5-scale) in less than 14 minutes and 15 seconds."),
    FAITHLESS_ENCOUNTER("Faithless Encounter", TaskTier.GRANDMASTER, "Vorkath", "Kill Vorkath without losing any prayer points."),
    THE_FREMENNIK_WAY("The Fremennik Way", TaskTier.GRANDMASTER, "Vorkath", "Kill Vorkath with only your fists."),
    VORKATH_SPEEDRUNNER("Vorkath Speed-Runner", TaskTier.GRANDMASTER, "Vorkath", "Kill Vorkath in less than 54 seconds."),
    CHAMBERS_OF_XERIC_CM_GRANDMASTER("Chambers of Xeric: CM Grandmaster", TaskTier.GRANDMASTER, "Chambers of Xeric (CM)", "Complete the Chambers of Xeric: Challenge Mode 150 times."),
    CHAMBERS_OF_XERIC_CM_SOLO_SPEEDRUNNER("Chambers of Xeric: CM (Solo) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (Solo) in less than 38 minutes and 30 seconds."),
    CHAMBERS_OF_XERIC_CM_5SCALE_SPEEDRUNNER("Chambers of Xeric: CM (5-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (5-scale) in less than 25 minutes."),
    CHAMBERS_OF_XERIC_CM_TRIO_SPEEDRUNNER("Chambers of Xeric: CM (Trio) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric (CM)", "Complete a Chambers of Xeric: Challenge Mode (Trio) in less than 27 minutes."),
    CHAMBERS_OF_XERIC_GRANDMASTER("Chambers of Xeric Grandmaster", TaskTier.GRANDMASTER, "Chambers of Xeric", "Complete the Chambers of Xeric 250 times."),
    CHAMBERS_OF_XERIC_SOLO_SPEEDRUNNER("Chambers of Xeric (Solo) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (Solo) in less than 17 minutes."),
    CHAMBERS_OF_XERIC_TRIO_SPEEDRUNNER("Chambers of Xeric (Trio) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (Trio) in less than 14 minutes and 30 seconds."),
    CHAMBERS_OF_XERIC_5SCALE_SPEEDRUNNER("Chambers of Xeric (5-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Chambers of Xeric", "Complete a Chambers of Xeric (5-scale) in less than 12 minutes and 30 seconds."),
    DEMON_WHISPERER("Demon Whisperer", TaskTier.GRANDMASTER, "K'ril Tsutsaroth", "Kill K'ril Tsutsaroth in a privately rented instance without ever being hit by his bodyguards."),
    ASH_COLLECTOR("Ash Collector", TaskTier.GRANDMASTER, "K'ril Tsutsaroth", "Kill K'ril Tsutsaroth 20 times in a privately rented instance without leaving the room."),
    INFERNO_GRANDMASTER("Inferno Grandmaster", TaskTier.GRANDMASTER, "Inferno", "Complete the Inferno 10 times."),
    THE_FLOOR_IS_LAVA("The Floor Is Lava", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without letting Jal-ImKot dig during any wave in the Inferno."),
    PLAYING_WITH_JADS("Playing with Jads", TaskTier.GRANDMASTER, "Inferno", "Complete wave 68 of the Inferno within 30 seconds of the first JalTok-Jad dying."),
    NO_LUCK_REQUIRED("No Luck Required", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without being attacked by TzKal-Zuk and without taking damage from a JalTok-Jad."),
    WASNT_EVEN_CLOSE("Wasn't Even Close", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without letting your hitpoints fall below 50 during any wave in the Inferno."),
    BUDGET_SETUP("Budget Setup", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without equipping a Twisted Bow within the Inferno."),
    NIBBLER_CHASER("Nibbler Chaser", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without using any magic spells during any wave in the Inferno."),
    FACING_JAD_HEADON_II("Facing Jad Head-on II", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without equipping any range or mage weapons before wave 69."),
    JAD_WHAT_ARE_YOU_DOING_HERE("Jad? What Are You Doing Here?", TaskTier.GRANDMASTER, "Inferno", "Kill Tzkal-Zuk without killing the JalTok-Jad which spawns during wave 69."),
    INFERNO_SPEEDRUNNER("Inferno Speed-Runner", TaskTier.GRANDMASTER, "Inferno", "Complete the Inferno in less than 65 minutes."),
    THE_VI_JAD_CHALLENGE("The VI Jad Challenge", TaskTier.GRANDMASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's sixth challenge."),
    TZHAARKETRAKS_SPEEDRUNNER("TzHaar-Ket-Rak's Speed-Runner", TaskTier.GRANDMASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's fifth challenge in less than 5 minutes."),
    IT_WASNT_A_FLUKE("It Wasn't a Fluke", TaskTier.GRANDMASTER, "TzHaar-Ket-Rak's Challenges", "Complete TzHaar-Ket-Rak's fifth and sixth challenges back to back without failing."),
    STOP_RIGHT_THERE("Stop Right There!", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat the Maiden of Sugadinti in the Theatre of Blood: Hard Mode without letting blood spawns create more than 15 blood trails."),
    PERSONAL_SPACE("Personal Space", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat the Pestilent Bloat in the Theatre of Blood: Hard Mode with a least 3 people in the room, without anyone in your team standing on top of each other."),
    ROYAL_AFFAIRS("Royal Affairs", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "In the Theatre of Blood: Hard Mode, complete the Nylocas room without ever letting the Nylocas Prinkipas change styles."),
    HARDER_MODE_I("Harder Mode I", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat Sotetseg in the Theatre of Blood: Hard Mode without anyone sharing the ball with anyone, without anyone dying, and without anyone taking damage from any of its other attacks or stepping on the wrong tile in the maze."),
    HARDER_MODE_II("Harder Mode II", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat Xarpus in the Theatre of Blood: Hard Mode after letting the exhumeds heal him to full health and without anyone in the team taking any damage."),
    NYLO_SNIPER("Nylo Sniper", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat Verzik Vitur's in the Theatre of Blood: Hard Mode without anyone in your team causing a Nylocas to explode by getting too close."),
    TEAM_WORK_MAKES_THE_DREAM_WORK("Team Work Makes the Dream Work", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "When Verzik Vitur in the Theatre of Blood: Hard Mode uses her yellow power blast attack while the tornadoes are active, have everyone get through the attack without taking damage. This cannot be completed with one player alive"),
    HARDER_MODE_III("Harder Mode III", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Defeat Verzik Vitur in the Theatre of Blood: Hard Mode without anyone attacking her with a melee weapon during her third phase."),
    PACK_LIKE_A_YAK("Pack Like a Yak", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode within the challenge time, with no deaths and without anyone buying anything from a supply chest."),
    THEATRE_HM_TRIO_SPEEDRUNNER("Theatre: HM (Trio) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode (Trio) with an overall time of less than 23 minutes."),
    THEATRE_HM_4SCALE_SPEEDRUNNER("Theatre: HM (4-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode (4-scale) with an overall time of less than 21 minutes."),
    THEATRE_HM_5SCALE_SPEEDRUNNER("Theatre: HM (5-Scale) Speed-Runner", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode (5-scale) with an overall time of less than 19 minutes."),
    THEATRE_OF_BLOOD_HM_GRANDMASTER("Theatre of Blood: HM Grandmaster", TaskTier.GRANDMASTER, "Theatre of Blood (HM)", "Complete the Theatre of Blood: Hard Mode 100 times."),
    PHOSANIS_VETERAN("Phosani's Veteran", TaskTier.GRANDMASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare 100 times."),
    PERFECT_PHOSANIS_NIGHTMARE("Perfect Phosani's Nightmare", TaskTier.GRANDMASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare while only taking damage from husks, power blasts and weakened Parasites. Also, without having your attacks slowed by the Nightmare Spores or letting a Sleepwalker reach Phosani's Nightmare."),
    PHOSANIS_SPEEDRUNNER("Phosani's Speedrunner", TaskTier.GRANDMASTER, "Phosani's Nightmare", "Defeat Phosani's Nighmare within 7 minutes."),
    CANT_WAKE_UP("Can't Wake Up", TaskTier.GRANDMASTER, "Phosani's Nightmare", "Kill Phosani's Nightmare 5 times in a row without leaving Phosani's Dream.");


    public final String name;
    public final TaskTier tier;
    public final String monster;
    public final String description;

    CombatTask(String name, TaskTier tier, String monster, String description)
    {
        this.name = name;
        this.tier = tier;
        this.monster = monster;
        this.description = description;
    }

    public static CombatTask getTask(String name) {
        name = name.toLowerCase();
        for (CombatTask td : values()) {
            if (td.name.toLowerCase().equals(name)) {
                return td;
            }
        }
        return null;
    }
}
